// if (true){
//    do something();
// } else {
//   do something();
// }

//const id = 3500;

// equal to 
if (id==3500){
    console.log('Benar');
} else {
    console.log('Salah');
}

// not equel
if (id!=100){
    console.log('Benar');
}else{
    console.log('Salah');
}

// equel to value and type 
if (id===100){
    console.log('Benar');
}else {
    console.log('Salah');
}

//if (id) {
//    console.log(`Nilai ID Adalah : ${id}`);
// }else {
//    console.log('Nilai ID Tidak Terdefinisi');
// }


if (id < 2000) {
    console.log('Benar');
} else {
    console.log('Salah');
}

const day = 'friday'
if (day == 'monday') {
    console.log('Day is monday');
}else if(day == 'saturday') {
    console.log('day is saturday');
}else{
    console.log('day is not monday and not saturday');
}